#baseurl = "http://outsidein.tech/"
baseurl = "https://oitech.github.io/outsidein.tech/"
languageCode = "en-us"
title = "Outside-In Tech"
theme = "hugo-type-theme"
disqusShortname = "outsideintech"
googleAnalytics = "UA-82433994-1"
# Posts per page
paginate = 20

# Pygments syntax highlighter
#PygmentsUseClasses = true
#PygmentsCodeFences = true

# TODO
# import old posts from wordpress using wordpress-to-hugo-exporter (https://gohugo.io/tools/)
# add popups like waitbutwhy
# gotemplate note working
# hugo feature - suggested posts (if you liked this, then you may like)

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
	author = "OITech"
	description = "TLDR explanations of technology"
	gravatar = "outsidein.tech@gmail.com"

	#headerText = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<br><br>Remove all header text in **config.toml** to disable this feature."
	# To add a header background to the main site, save your image under static/img/.
	# If now image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Licensed under Creative Commons (BY-SA 4.0)"
	#Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"

	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "outsidein.tech@gmail.com"
		behance = ""
		bitbucket  = ""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "oitech"
		googleplus = ""
		instagram = ""
		linkedin = ""
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""

[blackfriday]
	hrefTargetBlank = true
		
